# Generated by Django 5.2 on 2025-06-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='sin_email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('BOB', 'Bolivianos')], default='BOB', max_length=3),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='vehiculos',
            field=models.ManyToManyField(related_name='repuestos', to='repuestos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.PositiveIntegerField(),
        ),
    ]
